version: "1.0"
services: 
  apache2:
    build: /Users/gimbyeongcheon/Desktop/PetMeetsWorld/apache
    networks:
      myboard: 
        ipv4_address: 172.20.0.2
    restart: always
    environment:
      - VIRTUAL_HOST=www.petmeetsworld.com    
    ports: 
      - "80:80" 
  tomcat9:
    build: /Users/gimbyeongcheon/Desktop/PetMeetsWorld/tomcat
    networks:
      myboard:
        ipv4_address: 172.20.0.3
    restart: always
    environment:
      - VIRTUAL_HOST=www.petmeetsworld.com
    ports: 
      - "8080:8080"
  mysql:
    build: /Users/gimbyeongcheon/Desktop/PetMeetsWorld/mysql
    networks: 
      myboard: 
        ipv4_address: 172.20.0.4
    restart: always
    ports:
      - "3306:3306"
networks:
  myboard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"